# 继承基础配置
INHERIT: mkdocs_base.yml
site_name: "Hi3516CV610 开发者中心"
site_url: https://hivsdev.github.io/Hi3516CV610_doc/

site_description: Hi3516CV610 超高清智慧视觉 SoC 文档
site_author: HivsDev

repo_name: 前往GitHub编辑
repo_url: https://github.com/HivsDev/Hi3516CV610_doc
edit_uri: edit/main/docs/

copyright: >
  Documentation © 2026 HivsDev contributors —
  <a href="https://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA 4.0</a>

# 语言配置
plugins:
  - i18n:
      docs_structure: folder
      languages:
        - locale: zh-CN
          name: 中文
          default: true
          link: /
          site_name: "Hi3516CV610 开发者中心"
          theme:
            language: zh
  - search:
      lang:
        - zh

extra:
  version_selector:
    repo_path: Hi3516CV610_doc
    version: main

nav:
  - 概览: zh-CN/index.md
  - 快速入门:
      - 环境搭建: zh-CN/get-started/environment-setup.md
      - 快速开始: zh-CN/get-started/quick-start.md
  - 整体架构: zh-CN/overall-architecture/index.md
  - 参考案例:
      - Sample 指导说明: zh-CN/samples/sample-guide/Sample指导说明.md
      - 调试调优 - 硬件:
          - DDR3 参数配置: zh-CN/samples/debug-tuning/hardware/Hi3516CV610 DDR3 参数配置方法/Hi3516CV610 DDR3 参数配置方法.md
      - 调试调优 - BSP:
          - Flash 移植指南: zh-CN/samples/debug-tuning/bsp/基于fmcv100控制器的Flash移植指南/基于fmcv100控制器的Flash移植指南.md
          - 内存布局调整指南: zh-CN/samples/debug-tuning/bsp/内存布局调整指南/内存布局调整指南.md
          - BSP FAQ: zh-CN/samples/debug-tuning/bsp/BSP FAQ/BSP FAQ.md
          - 调试工具使用指南: zh-CN/samples/debug-tuning/bsp/Hi35xxVxxx 调试工具使用指南/Hi35xxVxxx 调试工具使用指南.md
          - 快速启动优化指南: zh-CN/samples/debug-tuning/bsp/Hi35xxVxxx 快速启动优化指南/Hi35xxVxxx 快速启动优化指南.md
      - 调试调优 - MPP:
          - 编码器图像质量调优指南: zh-CN/samples/debug-tuning/mpp/编码器图像质量调优指南/编码器图像质量调优指南.md
          - 性能/带宽/延时/内存调优指南: zh-CN/samples/debug-tuning/mpp/性能╱带宽╱延时╱内存调优指南/性能╱带宽╱延时╱内存调优指南.md
          - 智能编码自适应 使用说明: zh-CN/samples/debug-tuning/mpp/智能编码自适应 使用说明/智能编码自适应 使用说明.md
      - 调试调优 - PQ:
          - 图像自适应 使用说明: zh-CN/samples/debug-tuning/pq/图像自适应 使用说明/图像自适应 使用说明.md
          - 行车记录仪/无人机 图像调试 FAQ: zh-CN/samples/debug-tuning/pq/行车记录仪和无人机应用图像调试FAQ/行车记录仪和无人机应用图像调试FAQ.md
          - 智能 PQ 使用指导: zh-CN/samples/debug-tuning/pq/智能PQ 使用指导/智能PQ 使用指导.md
          - 3DNR 参数配置说明: zh-CN/samples/debug-tuning/pq/Hi3516CV610╱Hi3516CV608 3DNR参数配置说明/Hi3516CV610╱Hi3516CV608 3DNR参数配置说明.md
          - 图像质量测试标准: zh-CN/samples/debug-tuning/pq/Hisilicon IP Camera 图像质量测试标准/Hisilicon IP Camera 图像质量测试标准.md
          - ISP 图像调优指南: zh-CN/samples/debug-tuning/pq/ISP 图像调优指南/ISP 图像调优指南.md
          - ISP 颜色调优说明: zh-CN/samples/debug-tuning/pq/ISP 颜色调优说明/ISP 颜色调优说明.md
          - Sensor 调试指南: zh-CN/samples/debug-tuning/pq/Sensor 调试指南/Sensor 调试指南.md
  - API 参考:
      - 安全子系统:
          - 安全启动使用指南: zh-CN/api-reference/security/Hi35xxVxxx 安全启动使用指南/Hi35xxVxxx 安全启动使用指南.md
          - 安全子系统使用说明: zh-CN/api-reference/security/Hi35xxVxxx 安全子系统使用说明/Hi35xxVxxx 安全子系统使用说明.md
          - SELinux 开发指南: zh-CN/api-reference/security/SELinux开发指南/SELinux开发指南.md
      - BSP:
          - 裸烧及非裸烧升级 使用手册: zh-CN/api-reference/bsp/裸烧及非裸烧升级 使用手册/裸烧及非裸烧升级 使用手册.md
          - 外围设备驱动 操作指南: zh-CN/api-reference/bsp/外围设备驱动 操作指南/外围设备驱动 操作指南.md
          - 开发环境用户指南: zh-CN/api-reference/bsp/Hi35xxVxxx 开发环境用户指南/Hi35xxVxxx 开发环境用户指南.md
          - U-boot 移植应用开发指南: zh-CN/api-reference/bsp/Hi35xxVxxx U-boot 移植应用开发指南/Hi35xxVxxx U-boot 移植应用开发指南.md
          - UBI 文件系统使用指南: zh-CN/api-reference/bsp/UBI 文件系统使用指南/UBI 文件系统使用指南.md
      - ISP:
          - AIISP 开发参考: zh-CN/api-reference/isp/AIISP 开发参考/AIISP 开发参考.md
          - ISP 开发参考: zh-CN/api-reference/isp/ISP 开发参考/ISP 开发参考（1~5）.md
          - ISP FAQ: zh-CN/api-reference/isp/ISP FAQ/ISP FAQ.md
      - MPP:
          - 安全子系统 API 参考: zh-CN/api-reference/mpp/安全子系统 API 参考/安全子系统 API 参考.md
          - 开机声音使用指南: zh-CN/api-reference/mpp/开机声音使用指南/开机声音使用指南.md
          - 哭声检测 API 参考: zh-CN/api-reference/mpp/哭声检测 API参考/哭声检测 API参考.md
          - 芯片码率控制使用说明: zh-CN/api-reference/mpp/芯片码率控制使用说明/芯片码率控制使用说明.md
          - 音频组件 API 参考: zh-CN/api-reference/mpp/音频组件 API参考/音频组件 API参考.md
          - 智能编码使用指导: zh-CN/api-reference/mpp/智能编码使用指导/智能编码使用指导.md
          - DEVSTAT 开发参考: zh-CN/api-reference/mpp/DEVSTAT开发参考/DEVSTAT开发参考.md
          - MIPI 使用指南: zh-CN/api-reference/mpp/MIPI 使用指南/MIPI 使用指南.md
          - MPP 媒体处理软件 V6.0 开发参考: zh-CN/api-reference/mpp/MPP 媒体处理软件 V6.0 开发参考/0 前言.md
          - MPP 媒体处理软件 V6.0 FAQ: zh-CN/api-reference/mpp/MPP 媒体处理软件 V6.0 FAQ/MPP 媒体处理软件 V6.0 FAQ.md
          - RTC 应用指南: zh-CN/api-reference/mpp/RTC 应用指南/RTC 应用指南.md
          - SYS_CONFIG 配置指南: zh-CN/api-reference/mpp/SYS_CONFIG 配置指南/SYS_CONFIG 配置指南.md
      - SVP:
          - 智能视频处理软件 V1.0 开发参考: zh-CN/api-reference/svp/智能视频处理软件V1.0开发参考/智能视频处理软件V1.0开发参考.md
          - IVE API 参考: zh-CN/api-reference/svp/IVE API 参考/IVE API 参考.md
          - IVS API 参考: zh-CN/api-reference/svp/IVS API 参考/IVS API 参考.md
  - 硬件指南:
      - 硬件设计 Checklist (QFN): zh-CN/hardware-guide/board/Hi3516CV610 硬件设计 Checklist（QFN）/Hi3516CV610 硬件设计 Checklist（QFN）.md
      - 硬件设计用户指南 (QFN): zh-CN/hardware-guide/board/Hi3516CV610 硬件设计用户指南（QFN）/Hi3516CV610 硬件设计用户指南（QFN）.md
      - Demo 单板使用指南 (QFN): zh-CN/hardware-guide/board/Hi3516CV610 Demo 单板使用指南（QFN）/Hi3516CV610 Demo 单板使用指南（QFN）.md
  - 工具中心:
      - 音频质量调试工具: zh-CN/tools/audio-quality/音频质量调试工具使用指南/音频质量调试工具使用指南.md
      - 图像质量调试工具: zh-CN/tools/picture-quality/图像质量调试工具使用指南/图像质量调试工具使用指南.md
      - SVP_NPU:
          - 快速上手指南: zh-CN/tools/svp-npu/快速上手指南/快速上手指南.md
          - 驱动和开发环境安装指南: zh-CN/tools/svp-npu/驱动和开发环境安装指南/驱动和开发环境安装指南.md
          - 应用开发指南: zh-CN/tools/svp-npu/应用开发指南/应用开发指南.md
          - AMCT 使用指南 (Caffe): zh-CN/tools/svp-npu/AMCT使用指南（Caffe）/AMCT使用指南（Caffe）.md
          - AMCT 使用指南 (PyTorch): zh-CN/tools/svp-npu/AMCT使用指南（PyTorch）/AMCT使用指南（PyTorch）.md
          - ATC Graph 开发指南: zh-CN/tools/svp-npu/ATC Graph开发指南/ATC Graph开发指南.md
          - ATC 工具使用指南: zh-CN/tools/svp-npu/ATC工具使用指南/ATC工具使用指南.md
          - ATC 自定义算子开发指南: zh-CN/tools/svp-npu/ATC自定义算子开发指南/ATC自定义算子开发指南.md
          - MindCmd 使用指南: zh-CN/tools/svp-npu/MindCmd 使用指南/MindCmd使用指南.md
      - ToolPlatform:
          - BurnTool 工具使用指南: zh-CN/tools/tool-platform/BurnTool工具使用指南/BurnTool工具使用指南.md
          - ToolPlatform 工具平台使用指南: zh-CN/tools/tool-platform/ToolPlatform工具平台使用指南/ToolPlatform工具平台 使用指南.md
  - FAQ: zh-CN/FAQ/Hi3516CV610 FAQ.md
  - 其他:
      - 版本说明: zh-CN/others/versions/index.md
      - 贡献指南: zh-CN/others/instruction-manual/Instruction-manual.md